export const PATH = {
  MAIN: '/',
  LEARN: '/learn',
  LEARN_CHARTER: '/learn/charter',
  LEARN_OVERVIEW: '/learn/overview',
  LEARN_TECHNOLOGY: '/learn/technology',
  LEARN_ECCPOW: '/learn/eccpow',
  LEARN_ASIC_RESISTENCE: '/learn/asic-resistence',
  LEARN_PQ_SECURITY: '/learn/pq-security',
  LEARN_GREEN_VCA: '/learn/green-vca',
  LEARN_DESIGN_PRINCIPLE: '/learn/design-principle',
  LEARN_HOW_WORKS: '/learn/how-works',
  LEARN_TOKENOMICS: '/learn/tokenomics',
  LEARN_GOVERNANCE: '/learn/governance',
  LEARN_FAQ: '/learn/faq',
};
