export enum ABI {
  ETHEREUM_BRIDGE_ABI = 'ETHEREUM_BRIDGE_ABI',
  POLYGON_BRIDGE_ABI = 'POLYGON_BRIDGE_ABI',
  ERC20_ABI = 'ERC20_ABI',
  UNISWAPV2_ROUTER = 'UNISWAPV2_ROUTER',
  UNISWAPV2_PAIR = 'UNISWAPV2_PAIR',
  WRAPETH = 'WRAPETH',
}

export enum Field {
  INPUT = 'INPUT',
  OUTPUT = 'OUTPUT',
}
